using System.ComponentModel.DataAnnotations;

namespace Intex.Api.DTOs;

public record InterventionPlanRequest(
    [Required, StringLength(40)] string PlanCategory,
    [Required, StringLength(500)] string PlanDescription,
    [Required, StringLength(200)] string ServicesProvided,
    [Range(typeof(decimal), "0.01", "999999999.99")] decimal? TargetValue,
    DateOnly TargetDate,
    [Required, StringLength(20), RegularExpression(ValidationPatterns.InterventionStatus)] string Status,
    DateOnly? CaseConferenceDate);

public record ResidentRequest(
    [Required, StringLength(20), RegularExpression(ValidationPatterns.CaseCode)] string CaseControlNumber,
    [Required, StringLength(50), RegularExpression(ValidationPatterns.CaseCode)] string InternalCode,
    [Range(1, int.MaxValue)] int SafehouseId,
    [Required, StringLength(20), RegularExpression(ValidationPatterns.ResidentCaseStatus)] string CaseStatus,
    DateOnly DateOfBirth,
    [Required, StringLength(120)] string PlaceOfBirth,
    [Required, StringLength(60)] string Religion,
    [Required, StringLength(40), RegularExpression(ValidationPatterns.ResidentCaseCategory)] string CaseCategory,
    bool IsTrafficked,
    bool IsPhysicalAbuseCase,
    bool IsSexualAbuseCase,
    bool HasSpecialNeeds,
    [StringLength(200)] string? SpecialNeedsDiagnosis,
    bool FamilyIs4Ps,
    bool FamilySoloParent,
    bool FamilyIndigenous,
    bool FamilyInformalSettler,
    DateOnly DateOfAdmission,
    [Required, StringLength(80)] string ReferralSource,
    [StringLength(150)] string? ReferringAgencyPerson,
    [Required, StringLength(120)] string AssignedSocialWorker,
    [Required, StringLength(500)] string InitialCaseAssessment,
    [StringLength(80)] string? ReintegrationType,
    [StringLength(40)] string? ReintegrationStatus,
    [Required, StringLength(20), RegularExpression(ValidationPatterns.RiskLevel)] string InitialRiskLevel,
    [Required, StringLength(20), RegularExpression(ValidationPatterns.RiskLevel)] string CurrentRiskLevel,
    DateOnly? DateClosed,
    [StringLength(4000)] string? RestrictedNotes,
    [Required, MinLength(1)] List<InterventionPlanRequest> InterventionPlans);

public record InterventionPlanResponse(
    int Id,
    string PlanCategory,
    string PlanDescription,
    string ServicesProvided,
    decimal? TargetValue,
    DateOnly TargetDate,
    string Status,
    DateOnly? CaseConferenceDate);

public record ResidentResponse(
    int Id,
    string CaseControlNumber,
    string InternalCode,
    int SafehouseId,
    string SafehouseName,
    string CaseStatus,
    DateOnly DateOfBirth,
    string PlaceOfBirth,
    string Religion,
    string CaseCategory,
    bool IsTrafficked,
    bool IsPhysicalAbuseCase,
    bool IsSexualAbuseCase,
    bool HasSpecialNeeds,
    string? SpecialNeedsDiagnosis,
    bool FamilyIs4Ps,
    bool FamilySoloParent,
    bool FamilyIndigenous,
    bool FamilyInformalSettler,
    DateOnly DateOfAdmission,
    string ReferralSource,
    string? ReferringAgencyPerson,
    string AssignedSocialWorker,
    string InitialCaseAssessment,
    string? ReintegrationType,
    string? ReintegrationStatus,
    string InitialRiskLevel,
    string CurrentRiskLevel,
    DateOnly? DateClosed,
    string? RestrictedNotes,
    List<InterventionPlanResponse> InterventionPlans);
