import type { ResidentRequest } from '../../../api/types';

export function createResidentForm(safehouseId?: number): ResidentRequest {
  const today = new Date().toISOString().slice(0, 10);
  return {
    caseControlNumber: '',
    internalCode: '',
    safehouseId: safehouseId ?? 1,
    caseStatus: 'Active',
    sex: 'F',
    dateOfBirth: '2011-01-01',
    birthStatus: 'Marital',
    placeOfBirth: '',
    religion: '',
    caseCategory: 'Neglected',
    subCatOrphaned: false,
    isTrafficked: false,
    subCatChildLabor: false,
    isPhysicalAbuseCase: false,
    isSexualAbuseCase: false,
    subCatOsaec: false,
    subCatCicl: false,
    subCatAtRisk: false,
    subCatStreetChild: false,
    subCatChildWithHiv: false,
    isPwd: false,
    pwdType: '',
    hasSpecialNeeds: false,
    specialNeedsDiagnosis: '',
    familyIs4Ps: false,
    familySoloParent: false,
    familyIndigenous: false,
    familyParentPwd: false,
    familyInformalSettler: false,
    dateOfAdmission: today,
    referralSource: 'Government Agency',
    referringAgencyPerson: '',
    dateColbRegistered: '',
    dateColbObtained: '',
    assignedSocialWorker: '',
    initialCaseAssessment: '',
    dateCaseStudyPrepared: '',
    reintegrationType: '',
    reintegrationStatus: '',
    initialRiskLevel: 'Medium',
    currentRiskLevel: 'Medium',
    dateEnrolled: '',
    dateClosed: '',
    restrictedNotes: '',
    interventionPlans: [
      {
        planCategory: 'Psychosocial',
        planDescription: '',
        servicesProvided: '',
        targetValue: null,
        targetDate: today,
        status: 'Open',
        caseConferenceDate: '',
      },
    ],
  };
}
